import type { Metadata } from "next";
import { Roboto } from "next/font/google"; // Change to a valid font
import "./globals.css";
import { Navigation } from "./components/navigation";

const roboto = Roboto({
  subsets: ['latin'], // Specify the subsets you need
  weight: ['400', '700'], // Specify the weights you want to use
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} antialiased`}
      >
        <header className="bg-slate-900 text-white p-4 text-center">
          <Navigation/>
        </header>
        {children}
        <footer className="bg-slate-900 text-white p-4 text-center">
          <p>&copy Samcode</p>
        </footer>
      </body>
    </html>
  );
}
